version: "3.3"

services:
  dashboard_db:
    container_name: dashboard_db
    image: postgres:latest
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=dashboard
    ports:
      - 5532:5432